namespace: g8s

api:
  image_version: 0.0.1
  replicas: 3
  host: api.g8s.dev
  port: 3333
  svc:
    name: api
    port: 80 
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      memory: "512Mi"
      cpu: "100m"
