{{- $services := dict "api" .Values.api -}}
{{- range $svc, $values := $services }}
apiVersion: v1
kind: Service
metadata:
  name: {{$.Release.Name}}-{{ $svc }}-svc
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{$.Release.Name}}-{{ $svc }}
  ports:
    - name: {{ $svc }}
      protocol: TCP
      port: {{ $values.svc.port }}
      targetPort: {{ $values.port }}
  type: LoadBalancer
---
{{- end }}