apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: g8s
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3333
  type: LoadBalancer
